### ISSUE TITLE
Use Ansible Group module instead of user to create groups

### ISSUE THREAD

**Issue by johnroach** [Kong/ansible-role-kong#7]
Hi it looks like at:

https://github.com/Mashape/ansible-role-kong/blob/5352278b04412aac9ac55cedf2fe82cecedcf570/tasks/main.yml#L13

Should be the following:

```
- name: Ensure kong group is present
  group:
    name: "{{ kong_group }}"
    state: present
  become: yes
```
